#!/usr/bin/env bash
server {
        listen 80 default_server;  # This is the line that binds port 80 to all ipv4 addresses
        listen [::]:80 default_server;  # This is the line that binds port 80 to all ipv6 addresses

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }
}

